// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-StJcl-2yAaQFAy1oJ8JdLsGX7kn4yIc',
    appId: '1:179227010460:web:58902f27d934ea9f511459',
    messagingSenderId: '179227010460',
    projectId: 'storage-project-70ed0',
    authDomain: 'storage-project-70ed0.firebaseapp.com',
    storageBucket: 'storage-project-70ed0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpxDLr5XWrxJSzIxV3KfDF2_SY8Byi51E',
    appId: '1:179227010460:android:ca220ee0537a41ea511459',
    messagingSenderId: '179227010460',
    projectId: 'storage-project-70ed0',
    storageBucket: 'storage-project-70ed0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7bt2hdLtk_6oTOyq5vKzz5a1D1ylbfaI',
    appId: '1:179227010460:ios:6eb986309372a418511459',
    messagingSenderId: '179227010460',
    projectId: 'storage-project-70ed0',
    storageBucket: 'storage-project-70ed0.appspot.com',
    androidClientId: '179227010460-nio7nb9nbnbkjnm9qbdfo49uud6fo9c4.apps.googleusercontent.com',
    iosClientId: '179227010460-kfrgtfp03mbvo6gsahfgoifls6729ivp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
